# -*- coding: utf-8 -*-
"""Copy of NLP Binary Text Classification Pipeline with Scikit-Learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbD2GdT0mCe-lLtiSbvAxq_PIMlAvdBt
"""

!pip install pandas numpy matplotlib seaborn scikit-learn nltk wordcloud datasets

"""# Imports"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
import string
import re
import os

from wordcloud import WordCloud

import nltk
nltk.download('stopwords', quiet=True)
nltk.download('wordnet',   quiet=True)
nltk.download('punkt',     quiet=True)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix,
)

warnings.filterwarnings("ignore")
# %matplotlib inline
print("All imports successful.")

"""# Configuration

"""

CSV_PATH     = "data.csv"
TEXT_COL     = "comment_text"
LABEL_COL    = "toxic"
TEST_SIZE    = 0.20
RANDOM_STATE = 42
MAX_FEATURES = 10_000

HF_DATASET_NAME = "thesofakillers/jigsaw-toxic-comment-classification-challenge"

"""
# Data Loading"""

from datasets import load_dataset

print(f"[INFO] Loading dataset from Hugging Face: '{HF_DATASET_NAME}'")
raw_dataset = load_dataset(HF_DATASET_NAME, split='train')

df = raw_dataset.to_pandas()

df = df[[TEXT_COL, LABEL_COL]]
df[LABEL_COL] = df[LABEL_COL].apply(lambda x: 'toxic' if x >= 0.5 else 'not toxic')

df.columns = ["text", "label"]
df.dropna(subset=["text", "label"], inplace=True)
df["text"]  = df["text"].astype(str)
df["label"] = df["label"].astype(str)

print(f"Dataset shape : {df.shape}")
print(f"\nMissing values:\n{df.isnull().sum().to_string()}")

df.head(5)

class_dist = df["label"].value_counts().reset_index()
class_dist.columns = ["Class", "Count"]
class_dist["Percentage"] = (class_dist["Count"] / len(df) * 100).round(2)
print(class_dist.to_string(index=False))

fig, ax = plt.subplots(figsize=(10, 4))
ax.bar(class_dist["Class"], class_dist["Count"],
       color=sns.color_palette("viridis", len(class_dist)), edgecolor="white")
ax.set_xlabel("Class", fontsize=12)
ax.set_ylabel("Number of Samples", fontsize=12)
ax.set_title("Class Distribution", fontsize=14, fontweight="bold")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()

"""---
# Text Preprocessing

Each text goes through:
1. Lowercase conversion
2. Remove URLs and HTML tags
3. Remove punctuation and digits
4. Tokenisation
5. Stopword removal
6. Lemmatization
"""

lemmatizer = WordNetLemmatizer()
STOP_WORDS = set(stopwords.words("english"))

def preprocess_text(text: str) -> str:
    """Clean a single text string."""

    text = text.lower()

    text = re.sub(r"http\S+|www\S+|<[^>]+>", " ", text)

    text = text.translate(str.maketrans("", "", string.punctuation + string.digits))

    tokens = text.split()

    tokens = [t for t in tokens if t not in STOP_WORDS and len(t) > 2]

    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)

print("preprocess_text() defined.")

df["clean_text"] = df["text"].apply(preprocess_text)

print("Sample before → after preprocessing:\n")
for _, row in df.head(3).iterrows():
    print(f"  ORIGINAL : {row['text'][:130]}")
    print(f"  CLEANED  : {row['clean_text'][:130]}")
    print()

"""
# Word Cloud Visualisation

"""

all_text = " ".join(df["clean_text"])
wc_cfg   = dict(width=1000, height=450, background_color="white",
                max_words=150, colormap="viridis")

wc = WordCloud(**wc_cfg).generate(all_text)

plt.figure(figsize=(14, 5))
plt.imshow(wc, interpolation="bilinear")
plt.axis("off")
plt.title("Overall Word Cloud", fontsize=16, fontweight="bold")
plt.tight_layout()
plt.savefig("wordcloud_overall.png", dpi=150, bbox_inches="tight")
plt.show()
print("[INFO] Saved → wordcloud_overall.png")

classes = df["label"].unique()
n_cols  = 2
n_rows  = int(np.ceil(len(classes) / n_cols))

fig, axes = plt.subplots(n_rows, n_cols,
                         figsize=(14, 4.5 * n_rows))
axes = axes.flatten()

for idx, cls in enumerate(classes):
    cls_text = " ".join(df[df["label"] == cls]["clean_text"])
    if cls_text.strip():
        wc = WordCloud(**wc_cfg).generate(cls_text)
        axes[idx].imshow(wc, interpolation="bilinear")
    axes[idx].axis("off")
    axes[idx].set_title(f'Class: "{cls}"', fontsize=12, fontweight="bold")

for j in range(len(classes), len(axes)):
    axes[j].set_visible(False)

fig.suptitle("Per-Class Word Clouds", fontsize=16, fontweight="bold", y=1.01)
plt.tight_layout()
plt.savefig("wordclouds_per_class.png", dpi=150, bbox_inches="tight")
plt.show()
print("[INFO] Saved → wordclouds_per_class.png")

"""
# Feature Extraction

"""

TFIDF_PARAMS = dict(max_features=MAX_FEATURES, ngram_range=(1, 2), sublinear_tf=True)
COUNT_PARAMS = dict(max_features=MAX_FEATURES, ngram_range=(1, 2))

print("TF-IDF params  :", TFIDF_PARAMS)
print("Count params   :", COUNT_PARAMS)
print("\n(ngram_range=(1,2) means both unigrams and bigrams are used)")

"""---
##  Step 5 — Model Implementation

Two classifiers are evaluated:

| Model | Notes |
|---|---|
| **Multinomial Naive Bayes** | Probabilistic, fast, works well with count/frequency features |
| **Logistic Regression** | Discriminative, handles high-dimensional sparse features well |
"""

LR_PARAMS = dict(max_iter=1000, random_state=RANDOM_STATE, C=1.0)

print("Logistic Regression params:", LR_PARAMS)
print("Naive Bayes: default parameters (alpha=1.0 — Laplace smoothing)")

"""---
##  Step 6 — Experiment Setup (sklearn Pipelines)

Four combinations are defined, each as an `sklearn.Pipeline`:

1. TF-IDF + Naive Bayes  
2. CountVectorizer + Naive Bayes  
3. TF-IDF + Logistic Regression  
4. CountVectorizer + Logistic Regression  
"""

experiments = {
    "TF-IDF + Naive Bayes": Pipeline([
        ("vectorizer", TfidfVectorizer(**TFIDF_PARAMS)),
        ("classifier", MultinomialNB()),
    ]),
    "CountVectorizer + Naive Bayes": Pipeline([
        ("vectorizer", CountVectorizer(**COUNT_PARAMS)),
        ("classifier", MultinomialNB()),
    ]),
    "TF-IDF + Logistic Regression": Pipeline([
        ("vectorizer", TfidfVectorizer(**TFIDF_PARAMS)),
        ("classifier", LogisticRegression(**LR_PARAMS)),
    ]),
    "CountVectorizer + Logistic Regression": Pipeline([
        ("vectorizer", CountVectorizer(**COUNT_PARAMS)),
        ("classifier", LogisticRegression(**LR_PARAMS)),
    ]),
}

for name, pipe in experiments.items():
    print(f"  {name}")

"""
# Train-Test Split

80% training / 20% testing"""

X_train, X_test, y_train, y_test = train_test_split(
    df["clean_text"], df["label"],
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=df["label"]
)

CLASSES = sorted(df["label"].unique().tolist())

print(f"Train samples : {len(X_train):,}")
print(f"Test  samples : {len(X_test):,}")
print(f"Classes       : {CLASSES}")

"""
# Training, Evaluation & Confusion Matrices

"""

def evaluate_experiment(name, pipeline, X_train, X_test, y_train, y_test, classes):
    """Train a pipeline and return all evaluation metrics."""

    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    avg = "macro"

    metrics = {
        "accuracy" : accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred, average=avg, zero_division=0),
        "recall"   : recall_score(y_test, y_pred,    average=avg, zero_division=0),
        "f1"       : f1_score(y_test, y_pred,        average=avg, zero_division=0),
        "report"   : classification_report(y_test, y_pred, zero_division=0),
        "cm"       : confusion_matrix(y_test, y_pred, labels=classes),
    }

    print("=" * 65)
    print(f"  --- {name} ---")
    print("=" * 65)
    print(f"  Accuracy  : {metrics['accuracy']:.4f}")
    print(f"  Precision : {metrics['precision']:.4f}  (macro avg)")
    print(f"  Recall    : {metrics['recall']:.4f}  (macro avg)")
    print(f"  F1-Score  : {metrics['f1']:.4f}  (macro avg)")
    print(f"\n  Classification Report:\n")
    print(metrics["report"])

    fig_size = max(6, len(classes))
    fig, ax  = plt.subplots(figsize=(fig_size, fig_size - 1))
    sns.heatmap(
        metrics["cm"],
        annot=True, fmt="d", cmap="Blues",
        xticklabels=classes, yticklabels=classes,
        linewidths=0.5, ax=ax
    )
    ax.set_xlabel("Predicted Label", fontsize=11)
    ax.set_ylabel("True Label", fontsize=11)
    ax.set_title(f"Confusion Matrix — {name}", fontsize=13, fontweight="bold")
    plt.xticks(rotation=45, ha="right")
    plt.yticks(rotation=0)
    plt.tight_layout()
    fname = f"cm_{name.replace(' ', '_').replace('+', 'and')}.png"
    plt.savefig(fname, dpi=150, bbox_inches="tight")
    plt.show()
    print(f"  [INFO] Confusion matrix saved → {fname}\n")

    return metrics

print("evaluate_experiment() defined.")

"""# TF-IDF + Naive Bayes"""

all_results = {}

name = "TF-IDF + Naive Bayes"
all_results[name] = evaluate_experiment(
    name, experiments[name], X_train, X_test, y_train, y_test, CLASSES
)

"""# CountVectorizer + Naive Bayes"""

name = "CountVectorizer + Naive Bayes"
all_results[name] = evaluate_experiment(
    name, experiments[name], X_train, X_test, y_train, y_test, CLASSES
)

"""#TF-IDF + Logistic Regression"""

name = "TF-IDF + Logistic Regression"
all_results[name] = evaluate_experiment(
    name, experiments[name], X_train, X_test, y_train, y_test, CLASSES
)

"""# CountVectorizer + Logistic Regression"""

name = "CountVectorizer + Logistic Regression"
all_results[name] = evaluate_experiment(
    name, experiments[name], X_train, X_test, y_train, y_test, CLASSES
)

"""
#Final Comparison Summary

"""

rows = []
for name, m in all_results.items():
    rows.append({
        "Model Combination": name,
        "Accuracy" : round(m["accuracy"],  4),
        "Precision": round(m["precision"], 4),
        "Recall"   : round(m["recall"],    4),
        "F1-Score" : round(m["f1"],        4),
    })

summary_df = pd.DataFrame(rows).set_index("Model Combination")

summary_df.style.highlight_max(axis=0, color="#d4f1c4")

metrics_to_plot = ["Accuracy", "Precision", "Recall", "F1-Score"]
x      = np.arange(len(summary_df))
width  = 0.18
colors = ["#4C72B0", "#DD8452", "#55A868", "#C44E52"]

fig, ax = plt.subplots(figsize=(14, 6))
for i, metric in enumerate(metrics_to_plot):
    ax.bar(x + i * width, summary_df[metric], width,
           label=metric, color=colors[i], edgecolor="white", linewidth=0.7)

ax.set_xticks(x + width * 1.5)
ax.set_xticklabels(summary_df.index, rotation=15, ha="right", fontsize=10)
ax.set_ylim(0, 1.05)
ax.set_ylabel("Score", fontsize=12)
ax.set_title("Model Comparison — All Metrics", fontsize=14, fontweight="bold")
ax.legend(loc="lower right", fontsize=10)
ax.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.savefig("model_comparison.png", dpi=150, bbox_inches="tight")
plt.show()
print("[INFO] Saved → model_comparison.png")

best_name = summary_df["F1-Score"].idxmax()
best_f1   = summary_df.loc[best_name, "F1-Score"]

tfidf_avg = summary_df[summary_df.index.str.contains("TF-IDF")]["F1-Score"].mean()
count_avg = summary_df[summary_df.index.str.contains("Count")]["F1-Score"].mean()
best_vec  = "TF-IDF" if tfidf_avg >= count_avg else "CountVectorizer"

nb_avg  = summary_df[summary_df.index.str.contains("Naive Bayes")]["F1-Score"].mean()
lr_avg  = summary_df[summary_df.index.str.contains("Logistic")]["F1-Score"].mean()
best_clf = "Logistic Regression" if lr_avg >= nb_avg else "Naive Bayes"

print("=" * 65)
print("  NARRATIVE SUMMARY")
print("=" * 65)
print(f""")
Best overall combination : {best_name}  (F1 = {best_f1:.4f})
Best vectorization method: {best_vec}   (avg F1 → TF-IDF: {tfidf_avg:.4f}, Count: {count_avg:.4f})
Best classifier          : {best_clf}   (avg F1 → LR: {lr_avg:.4f}, NB: {nb_avg:.4f})

""")